Traceback (most recent call last):
  File "/app/im/cryptodatadownload/data/load/test/test_loader.py", line 47, in test1
    actual = cdd_loader.read_data("binance", "BTC/USDT", "OHLCV")
  File "/app/im/cryptodatadownload/data/load/loader.py", line 104, in read_data
    s3fs = hs3.get_s3fs(self._aws_profile)
  File "/app/helpers/s3.py", line 390, in get_s3fs
    aws_credentials = get_aws_credentials(*args, **kwargs)
  File "/app/helpers/s3.py", line 321, in get_aws_credentials
    config = _get_aws_config(file_name)
  File "/app/helpers/s3.py", line 222, in _get_aws_config
    dbg.dassert_file_exists(file_name)
  File "/app/helpers/dbg.py", line 550, in dassert_file_exists
    _dfatal(txt, msg, *args)
  File "/app/helpers/dbg.py", line 115, in _dfatal
    dfatal(dfatal_txt)
  File "/app/helpers/dbg.py", line 61, in dfatal
    raise assertion_type(ret)
AssertionError:
################################################################################
* Failed assertion *
File '/app/home/.aws/credentials' doesn't exist
################################################################################
